services:
  postgres:
    image: postgres:16-alpine
    container_name: nestjs_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestjs_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - nestjs-network

volumes:
  postgres_data:

networks:
  nestjs-network: