CREATE TABLE IF NOT EXISTS wishlist (
  id SERIAL PRIMARY KEY,
  id_user INT NOT NULL,
  id_product VARCHAR (50) NOT NULL,
  create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  is_active BOOLEAN NOT NULL DEFAULT TRUE
  update_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
